### ISSUE TITLE
Server always restarting as TDM crossfire

### ISSUE THREAD

**Issue by gundogfan** [rtxa/agmodx#30]
As the title says, the server will always restart as tdm crossfire making impossible to have a specific gamemode sv running 24/7.

Steps to reproduce it:

1- Set `sv_ag_gamemode` and `sv_ag_allowed_gamemodes` (in **startup_server.cfg**) as `arena` or any other gamemode.
2- Run or restart the server.

The server will run as TDM no matter what unless you change it manually through vote/rcon.

But, if instead of **startup_server.cfg** we use **amxx.cfg**, it will remain as TDM as well but at least it _will_ change to the desired gamemode right after we change the map.

I also noticed it restarts in crossfire, regardless of how what's written in **mapcycle.txt**

Issue does not occur in original AG.

**Comment by rtxa** [comment]
After investigating the issue, unfortunately this enters in the category of **"Known limitation"**, `server.cfg` gets executed before AG Mod X CVars are registered, so it's ignored. Changing the map after server start is a good workaround.

I can't hook `GameDLLInit` from AMXX to register AG Mod X CVars and fix the issue without using ReHLDS exclusively (Not so sure) or Orpheu (which is incompatible with ReHLDS). I would add into the **FAQ** about this issue and his workaround with amxx.cfg. 

This probably can be fixed by hardcoding in BugfixedHL but that solution wouldn't be so elegant, a better solution would be to expose an API like ReGameDLL does and export it as  a module for AMXX, and manage everything from there. I'm afraid that would take time, but HL community would benefit from it (and several mods).

About mapcycle.txt, this is something that happens too in vanilla HLDS? Maybe something to do with hlds.exe startup parameters like using `+map crossfire`?

**Comment by rtxa** [comment]
Luckily, after doing some tests, I got it fixed in the latest commit 15da00ff7048dadea20bc824b33b30f192549674. Please, let me know if this working as expected by downloading it from [here](https://github.com/rtxa/agmodx/actions/runs/10687776173). @gundogfan @Safety1st
