### ISSUE TITLE
Feature request: More control over voteable CVARs

### ISSUE THREAD

**Issue by execut4ble** [rtxa/agmodx#48]
Hey, great work on this project so far! 

At the moment there is `sv_ag_vote_setting 1` which controls whether or not you can vote for a lot of "general" server settings, mostly those starting with mp_

This is mostly consistent with AG 6.6, but there are some differences:
- Voting for `sv_maxspeed`. It seems like this vote has no effect in AG 6.6 if it passes, which is probably a bug, but in AG Mod X it can override the server's setting. This is quite dangerous especially if you're running a movement server (Kreedz), people may change this to get unfair advantage.
- New CVARs: these new settings are all grouped with `sv_ag_vote_setting`. For example with `mp_bunnyhop`, this could also be potentially dangerous in some scenarios, for the same reason as above.

If I set `sv_ag_vote_setting` to 0, I can prevent players from voting these settings, but then I also lose the ability to vote for things such as `mp_timelimit`, probably one of the most useful things to be able to vote for. Therefore it would be nice to have more control over voteable CVARs.

A few suggested solutions:
- Separate mp_ and sv_ CVARs under different `sv_ag_vote_settings` levels. For example, AG 6.7 has sv_ag_vote_setting 2 which is basically a new "level" that allows to vote among 100+ gameplay cvars, most of the mp_ and some sv_ settings.
- Keep the same `sv_ag_vote_setting` behavior, but exclude `mp_timelimit`. There are already CVARs `sv_ag_vote_mp_timelimit_low` and `sv_ag_vote_mp_timelimit_high`, maybe a new CVAR could be added to allow/disallow voting for `mp_timelimit` altogether.
- Add a setting for each voteable CVAR to be able to define exactly what is voteable and what isn't.

**Comment by rtxa** [comment]
I'm glad to hear you like it!

About the settings, I need some time to digest this idea, but I'll try to answer the best I can.
1. You’re right that allowing votes like `sv_maxspeed` may not be suitable for some servers. Perhaps adding the cvar `sv_ag_disable_votes "sv_maxspeed;mp_bunnyhop"` _(naming needs to be improved)_ would address this situation? I'm in doubt about adding `sv_ag_allowed_votes` because of how many votes there are already but who knows.
2. I'm not so sure about adding a new level for `sv_ag_vote_settings` or adding new settings for individual votes, but I'll would like to see how AG 6.7 implements this to see if it's worth it. If you could share the repo or documentation about this feature, that would be great.
3. Excluding `mp_timelimit` from `sv_ag_vote_settings` may upset people who rely on this feature. Now that you mention about `sv_ag_vote_mp_timelimit_low` and `sv_ag_vote_mp_timelimit_high`, perhaps adjusting these values could serve as a workaround to disable it?
3. Adding settings for each vote gives you more control but it would fill the cvar list which is already big and people would always want more. I think 1. address this too.

Thanks for reporting these issues, feedback is always appreciated!

**Comment by execut4ble** [comment]
Good points, I like the first option too, essentially a voteable CVAR blacklist.

The AG 6.7 repo is here
https://github.com/fireblizzard/agmod/blob/bf06e4ffd31c1427784685118820e15552803bcb/dlls/agglobal.cpp#L137

Not sure if this has the full implementation since naz chose to continue parts of it closed-source, as far as I know.

**Comment by rtxa** [comment]
Added `sv_ag_disable_votes` https://github.com/rtxa/agmodx/commit/16092303534d69dda734310a09ee7218ca0bcf61. 

Let me know if it works as expected from here https://github.com/rtxa/agmodx/actions/runs/11415381872

Not sure how useful is to have those CVar flags, but the setting idea could be useful in the future if we know what cvars are really useful to enable/disable. Still, `sv_ag_disable_votes` should be good enough for most cases.

**Comment by execut4ble** [comment]
Works well, thanks!
