### ISSUE TITLE
agnextmode is not working properly

### ISSUE THREAD

**Issue by execut4ble** [rtxa/agmodx#49]
agnextmode doesn't seem to work. If I add an argument, for example `agnextmode tdm`, it says the vote is invalid.

If I issue agnextmode without any arguments, it clears the gamemode completely. Not sure if this is intended, but it should only allow voting for whatever is defined by `sv_ag_allowed_gamemodes`

![image](https://github.com/user-attachments/assets/990b3583-f30b-4e14-bb94-7e9eb23be26d)

**Comment by rtxa** [comment]
Looks like it's not being updated on real-time, I'll look into it. Thanks for reporting!

**Comment by rtxa** [comment]
Fixed in https://github.com/rtxa/agmodx/commit/2ab1ed9c3860ef49f707ce303aca48a7663de6cd https://github.com/rtxa/agmodx/commit/e580d17095b5d6697634322444f0d8b3f2597a2e. Let me know if it works as expected by downloading latest artifact from GitHub Actions https://github.com/rtxa/agmodx/actions/runs/11414853897

One observation, you can't disable game mode votes with`sv_ag_allowed_gamemodes` on the fly in the original mod, so I guess this is an improvement.

Still, I need to refactor how I can tell a game mode is disabled because I use the gTrieVoteList to check if it exists (because vote is added only if the game mode has been loaded correctly) and `sv_ag_allowed_gamemodes` can be unreliable since it allows invalid entries. This refactor would also benefit CVar `sv_ag_disabled_votes`, so maybe we can kill two birds in one stone.

**Comment by execut4ble** [comment]
Yep, it works as expected now. Thanks!
